### ISSUE TITLE
Website server not responding

### ISSUE THREAD

**Issue by JamesSwift** [didrocks/website#13]
Hi for at least the last 3 days your website at didrocks.fr has been inaccessible. Just fyi

**Comment by didrocks** [comment]
Thanks for reaching! As I’m self-hosted and I recently moved house, I had to move in between to a remote server. It’s back now! :)

**Comment by JamesSwift** [comment]
Awesome. I self host a load of stuff too. As a tip, you might consider using cloudflare as a free simple drop-in cdn for your site. It can ease the load on your connection, as well as cover for times that your server is offline.
